// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ArchiveStackPayload struct {
	Ok bool `json:"ok"`
}

type CreateStackInput struct {
	Name string  `json:"name"`
	Slug *string `json:"slug,omitempty"`
}

type CreateStackPayload struct {
	Stack *Stack `json:"stack"`
}

type Mutation struct {
}

type Query struct {
}

type Stack struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Slug       string     `json:"slug"`
	CreatedAt  time.Time  `json:"createdAt"`
	ArchivedAt *time.Time `json:"archivedAt,omitempty"`
}
