// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Stack struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	CreatedAt  time.Time          `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}
